# runtime: python39
# entrypoint: gunicorn -b :$PORT main:app
# env_variables:
#   GINICORN_PORT: 8080
# runtime_config:
#       operating_system: "ubuntu22"
# handlers:
# - url: /.*
#   static_files: dist/lighthouse-webapp/index.html
#   upload: dist/lighthouse-webapp/index.html
# - url: /
#   static_dir: dist/lighthouse-webapp
runtime: nodejs20
